### PR TITLE
remove useless props

### PR DESCRIPTION
**Pull request by GHopperMSK**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #47

### CODE REVIEW

**Comment by samdark** [comment]
Merged. Thanks!

**Comment by machour** [comment]
Maybe this should be reverted, see https://github.com/yiisoft/yii-web/issues/51

**Comment by philippfrenzel** [comment]
Here the error code:
`
in /app/vendor/yiisoft/yii-core/src/base/Component.php:212

Stack trace:
#0 /app/vendor/yiisoft/yii-console/src/Application.php(113): yii\base\Component->__set('requestedRoute', '')
#1 /app/vendor/yiisoft/yii-core/src/base/Application.php(532): yii\console\Application->handleRequest(Object(yii\console\Request))
#2 /app/vendor/yiisoft/yii-console/bin/yii(29): yii\base\Application->run()
#3 /app/vendor/yiisoft/yii-console/bin/yii(30): {closure}()
#4 {main}
`

**Comment by GHopperMSK** [comment]
https://github.com/yiisoft/yii-core/issues/47#issuecomment-466388146

**Comment by philippfrenzel** [comment]
Hi, yiisoft/yii-console Application references at least the $requestedRoute variable... if you wanna remove it here, maybe you should add it in yii-console and yii-web then?
Cheers Philipp

**Comment by hiqsol** [comment]
Reverted it back.
At the moment these props are used at least in `yii-web` and `yii-debug`.
These props are clumsy and will be removed indeed but later after appropriate refactoring.

**Pull request merged**
