### PR TITLE
ArrayHelper::remove() enchancement

### PR DESCRIPTION
**Pull request by GHopperMSK**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #72

### CODE REVIEW

**Comment by samdark** [comment]
That's a good enhancement but could be a bit controversial. What if I want to use a key that has dots in it?

**Comment by GHopperMSK** [comment]
I suppose next logic - if `$path` is a string and array key `$path` exists than delete it, otherwise  follow the path and delete its endpoint.

```
...
public static function remove(&$array, $path, $default = null)
{
    if (!is_array($path)) {
        $path = isset($array[$path]) ? array($path) : explode('.', $path);
    }

    while (count($path) > 1) {
        $key = array_shift($path);
        if (!isset($array[$key]) || !is_array($array[$key])) {
            return $default;
        }
        $array = &$array[$key];
    }

    $key = array_shift($path);
    $ret = $array[$key] ?? $default;
    unset($array[$key]);

    return $ret;
}
```

**Comment by machour** [comment]
@GHopperMSK What if I have both "foo.bar" & ["foo"]["bar"] entries in my array ? :/
Maybe adding a new method would be better.

**Comment by GHopperMSK** [comment]
> @GHopperMSK What if I have both "foo.bar" & ["foo"]["bar"] entries in my array ? :/
> Maybe adding a new method would be better.

We just will add note in phpDoc

`
Note that if the array already has an element `x.y.z`, then its value will be deleted instead of going through the sub-arrays. So it is better to be done specifying an array of key names like `['x', 'y', 'z']`.
`

It explains such situation.

**Comment by samdark** [comment]
Arrays are here now: https://github.com/yiisoft/arrays

**Pull request closed without merging**
