### PR TITLE
Removed HTTP implementation from the core

### PR DESCRIPTION
**Pull request by samdark**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | ?
| Fixed issues  |

### CODE REVIEW

**Comment by kids-return** [comment]
Http related exceptions can also be considered moving to `http` repo

**Comment by schmunk42** [comment]
If moved, please link to the commit in `http` where this code is re-added.

**Comment by samdark** [comment]
This code won't be re-added right now. We'll depend on PSR-7 and PSR-17.

**Comment by samdark** [comment]
See https://github.com/yiisoft/yii-auth-client/pull/9

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-web/pull/52

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-core/commit/45be7738e907be9b68df092bfa3db752fb548516

**Pull request closed without merging**
