### PR TITLE
Changed `init()` signature to follow `Initiable` interface - validators.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes

### CODE REVIEW

**Comment by rob006** [comment]
Shouldn't we fix this everywhere, instead of in 2 random classes only?

**Comment by hiqsol** [comment]
Of course, it will be fixed.
All PRs appreciated very much!

**Comment by tecnoterabyte** [comment]
The truth that all the comments of @ rob006 are negative, in any subject or case, send this small correction not because it is random, but because the application that I am testing uses these validators, if you know so much welcome all your pr instead of so much criticizes, what he does is pure talk.

**Comment by hiqsol** [comment]
And actually, it's there (in all validators but these two) already.

**Comment by hiqsol** [comment]
No @tecnoterabyte. Any constructive critics is appreciated and welcome.
@rob006 is constructive indeed!

**Comment by hiqsol** [comment]
@terabytesoftw Thank you!

**Comment by rob006** [comment]
> The truth that all the comments of @rob006 are negative

That is the point of code review - criticism. If you think that any criticism is negative, you will have really hard time in open source contribution...

> but because the application that I am testing uses these validators

Then again - wouldn't be more pragmatic to fix it everywhere? It should be relatively easy with search&replace, and you will not need to open separate PR and wait whole day for fixing this in upstream - it will save everyone's time, especially yours (this is already your second PR like that). ;]

**Pull request merged**
