### PR TITLE
Undefined variable: aliases

### PR DESCRIPTION
**Pull request by hughcube**
Undefined variable: aliases

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by hiqsol** [comment]
No. It's an important line.
It merges aliases collected with composer-config-plugin from autoloadable namespaces.

Please explain how do you get the error and I'll think how to fix it.

**Comment by hughcube** [comment]
composer update --prefer-dist

{
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php": ">=7.1.0",
    "ext-libxml": "*",
    "ext-json": "*",
    "yiisoft/yii-web": "dev-master",
    "yiisoft/yii-console": "dev-master",
    "yiisoft/di": "^3.0@dev",
    "yiisoft/log": "^3.0@dev",
    "yiisoft/cache": "^3.0@dev",
    "yiisoft/active-record": "^3.0@dev",
    "yiisoft/yii-swiftmailer": "^3.0@dev",
    "yiisoft/yii-redis":"*",
    "vlucas/phpdotenv": "*",
    "hiqdev/composer-config-plugin": "*"
  },
  "require-dev": {
  },
  "config": {
    "process-timeout": 1800,
    "github-protocols": [
      "https"
    ],
    "secure-http": false,
    "fxp-asset": {
      "enabled": true,
      "installer-paths": {
        "npm-asset-library": "vendor/npm",
        "bower-asset-library": "vendor/bower",
        "npm-searchable": false,
        "bower-searchable": false
      }
    }
  },
  "extra": {
    "config-plugin": {
      "common": [
        "common/config/main.php"
      ],
      "api": [
        "$common",
        "api/config/main.php"
      ],
      "backend": [
        "$common",
        "backend/config/main.php"
      ],
      "console": [
        "$common",
        "console/config/main.php"
      ],
      "frontend": [
        "$common",
        "frontend/config/main.php"
      ]
    }
  },
  "autoload": {
    "psr-4": {
      "common\\": "common",
      "api\\": "api",
      "backend\\": "backend",
      "frontend\\": "frontend",
      "console\\": "console"
    }
  }
}

**Comment by hughcube** [comment]
Can you tell me where the variable comes from?


/usr/local/bin/proxychains4 /usr/local/bin/php -f /usr/local/bin/composer update --prefer-dist
[proxychains] config file found: /usr/local/etc/proxychains.conf
[proxychains] preloading /usr/local/Cellar/proxychains-ng/4.13/lib/libproxychains4.dylib
[proxychains] DLL init: proxychains-ng 4.13
Loading composer repositories with package information
Warning: Accessing packages.developer.caibeitv.cn over http which is an insecure protocol.
[proxychains] Strict chain  ...  127.0.0.1:1086  ...  packages.developer.caibeitv.cn:80  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1086  ...  packages.developer.a165.net:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:1086  ...  repo.packagist.org:443  ...  OK
Updating dependencies (including require-dev)
Package operations: 21 installs, 0 updates, 0 removals
  - Installing hiqdev/composer-config-plugin (0.2.5): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing yiisoft/cache (dev-master b2a5408): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing yiisoft/di (dev-master 3149e64): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing yiisoft/log (dev-master 7764e39): Loading from cache
  - Installing yiisoft/yii-core (dev-master 6439b98): Loading from cache
  - Installing yiisoft/view (dev-master 89e2eee): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing yiisoft/yii-web (dev-master 77f7bff): Loading from cache
  - Installing yiisoft/yii-console (dev-master 9a3c376): Loading from cache
  - Installing yiisoft/db (dev-master 8cb4f6a): Loading from cache
  - Installing yiisoft/active-record (dev-master a3715c2): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing egulias/email-validator (2.1.5): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.1.2): Loading from cache
  - Installing yiisoft/yii-swiftmailer (dev-master 7b95876): Loading from cache
  - Installing yiisoft/core (dev-master 6439b98): Loading from cache
  - Installing yiisoft/yii-redis (dev-master c29c9e9): Loading from cache
  - Installing vlucas/phpdotenv (v2.5.1): Loading from cache
[proxychains] Strict chain  ...  127.0.0.1:1086  ...  packagist.org:443  ...  OK
yiisoft/yii-core suggests installing ezyang/htmlpurifier (version '^4.6' required at 'yii\helpers\HtmlPurifier' for 'html' data format support (e.g. 'yii\i18n\Formatter:asHtml()' and 'yii\helpers\StringHelper::truncateHtml()'))
yiisoft/yii-web suggests installing yiisoft/yii2-coding-standards (you can use this package to check for code style issues when contributing to yii)
swiftmailer/swiftmailer suggests installing true/punycode (Needed to support internationalized email addresses, if ext-intl is not installed)
yiisoft/core suggests installing ezyang/htmlpurifier (version '^4.6' required at 'yii\helpers\HtmlPurifier' for 'html' data format support (e.g. 'yii\i18n\Formatter:asHtml()' and 'yii\helpers\StringHelper::truncateHtml()'))
Writing lock file
Generating autoload files
Assembling config files

                               
  [ErrorException]             
  Undefined variable: aliases  
                               

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by hiqsol** [comment]
> why use hiqdev/composer-config-plugin to manage configuration

First of all you don't have to. You can prepare your application config any way you like.
As you can see composer-config-plugin is require-dev'ed so it is not required to run framework.
The plugin is recommended for application but not required.

> he is very inflexible

Why do you think so? Do you know better solutions?

**Comment by hughcube** [comment]
Using a .php file as a configuration, the point is that he has the flexibility to configure dynamic values, but there is no way to use hiqdev/composer-config-plugin

example

- 'params' => [
-         'date' => date('Y-m-d'),
-  ]
- 

generate

- 'params' =>
-   Array (
-     'date' => '2018-09-03',
-     'app.id' => 'core',
-     'app.name' => 'Core',
-     'app.language' => 'en',
-     'logger.traceLevel' => 0,
-   ),

However, I don't like big configuration myself. I currently use a class to inherit the corresponding base class.
Like this

- Class UrlManager extends \yii\web\UrlManager
- {
-     Use InstanceTrait;
-     Public $enablePrettyUrl = true;
-     Public $showScriptName = false;
-    Public $enableStrictParsing = true;
- }


You need to modify the configuration when you need to modify it. If you don't need it, you can use the default framework. The previous version 2.0 is very good, but the psr standard is not used, which makes many third-party packages not work well.


I don't have a better idea, just a small opinion.

**Comment by hiqsol** [comment]
> to configure dynamic values, but there is no way to use hiqdev/composer-config-plugin

No. It is indeed possible. Defines files are loaded as is on every run so it can be used to achieve such behavior. Please see: 
https://github.com/yiisoft/yii-core/blob/a6f582b175fe5cdd35817621ef9e225af5ece6e0/config/defines.php#L6

In general composer-config-plugin is a feature that you can choose to use or not. It's up to you.

**Comment by hiqsol** [comment]
Concerning your error. As you can see in your case latest release version is installed and it produces such error. While dev version is required in `composer.json`.

**Comment by hughcube** [comment]
But without this, the 3.0 version configuration is very troublesome.

**Comment by hiqsol** [comment]
> But without this, the 3.0 version configuration is very troublesome

What are the troubles?
This problem you describe is caused by your proxying tool.
And I hope it is solvable. I'll make a release of composer-config-plugin that should help.
I'm closing this PR. If you have problems please create an issue.

**Pull request closed without merging**
